#!/usr/bin/env zsh

# Bourgie DSL Compiler
# Compiles DSL files to oh-my-posh YAML configurations

# Get script directory
SCRIPT_DIR="${0:A:h}"

# Source the DSL engine
source "$SCRIPT_DIR/bourgie-dsl.zsh"

# Enhanced compiler with validation and error handling
function dsl_compile_enhanced() {
    local input_file="$1"
    local output_file="$2"
    local validate_only=false
    
    # Parse options
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --validate-only|-v)
                validate_only=true
                shift
                ;;
            --output|-o)
                output_file="$2"
                shift 2
                ;;
            *)
                if [[ -z "$input_file" ]]; then
                    input_file="$1"
                elif [[ -z "$output_file" ]]; then
                    output_file="$1"
                fi
                shift
                ;;
        esac
    done
    
    # Set default output file
    if [[ -z "$output_file" ]]; then
        if [[ -n "$input_file" ]]; then
            output_file="${input_file%.*}-compiled.yaml"
        else
            output_file="bourgie-compiled.yaml"
        fi
    fi
    
    echo "🏗️  Bourgie DSL Compiler"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    
    # Load and validate input file
    if [[ -n "$input_file" ]]; then
        echo "📂 Input:  $input_file"
        if ! dsl_load "$input_file"; then
            echo "❌ Failed to load DSL file"
            return 1
        fi
    else
        echo "📂 Input:  <interactive/example>"
        # Use example configuration
        dsl_example >/dev/null
    fi
    
    echo "📄 Output: $output_file"
    
    # Validate DSL state
    if ! dsl_validate; then
        echo "❌ DSL validation failed"
        return 1
    fi
    
    if [[ "$validate_only" == "true" ]]; then
        echo "✅ DSL validation successful"
        return 0
    fi
    
    # Compile to YAML
    if dsl_compile_to_yaml "$output_file"; then
        echo "✅ Compilation successful"
        
        # Validate generated YAML
        if dsl_validate_yaml "$output_file"; then
            echo "✅ Generated YAML is valid"
        else
            echo "⚠️  Warning: Generated YAML may have issues"
        fi
        
        return 0
    else
        echo "❌ Compilation failed"
        return 1
    fi
}

# Validate DSL state
function dsl_validate() {
    local errors=0
    
    # Check if we have any blocks
    if [[ ${#BOURGIE_DSL_BLOCKS[@]} -eq 0 ]]; then
        echo "❌ No prompt blocks defined"
        ((errors++))
    fi
    
    # Check if we have any segments
    if [[ ${#BOURGIE_DSL_SEGMENTS[@]} -eq 0 ]]; then
        echo "❌ No segments defined"
        ((errors++))
    fi
    
    # Validate color references
    for segment in "${BOURGIE_DSL_SEGMENTS[@]}"; do
        # Extract color references (simple check)
        local colors=$(echo "$segment" | grep -o "foreground: [^']*" | cut -d' ' -f2-)
        for color in $colors; do
            color="${color//\'}"  # Remove quotes
            if [[ "$color" != "transparent" ]] && [[ ! "$color" =~ ^#[0-9A-Fa-f]{6}$ ]] && [[ -z "${BOURGIE_COLORS[$color]}" ]]; then
                echo "⚠️  Unknown color reference: $color"
            fi
        done
    done
    
    if [[ $errors -gt 0 ]]; then
        echo "❌ Found $errors validation errors"
        return 1
    fi
    
    echo "✅ DSL validation passed"
    return 0
}

# Enhanced YAML compilation
function dsl_compile_to_yaml() {
    local output_file="$1"
    
    # Generate header with metadata
    local yaml_config="# Generated by Bourgie DSL Compiler
# Generated on: $(date)
# yaml-language-server: \$schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

palette:"
    
    # Add color palette (sorted for consistency)
    local sorted_colors=(${(ko)BOURGIE_COLORS})
    for color_name in "${sorted_colors[@]}"; do
        local color_value="${BOURGIE_COLORS[$color_name]}"
        if [[ "$color_value" != "transparent" ]]; then
            yaml_config="$yaml_config
    primary_${color_name}: '$color_value'"
        fi
    done
    
    # Add console title
    yaml_config="$yaml_config
console_title_template: '{{ .Shell }} in {{ .Folder }}'
blocks:"
    
    # Process blocks and segments
    local current_block_segments=()
    local block_index=0
    
    for block in "${BOURGIE_DSL_BLOCKS[@]}"; do
        yaml_config="$yaml_config$block"
        
        # Add segments for this block (simplified approach)
        # In a full implementation, we'd track which segments belong to which block
        for segment in "${BOURGIE_DSL_SEGMENTS[@]}"; do
            yaml_config="$yaml_config$segment"
        done
        
        ((block_index++))
    done
    
    # Add configuration footer
    yaml_config="$yaml_config
version: 3
final_space: true"
    
    # Write to file with error handling
    if echo "$yaml_config" > "$output_file" 2>/dev/null; then
        return 0
    else
        echo "❌ Failed to write output file: $output_file"
        return 1
    fi
}

# Validate generated YAML
function dsl_validate_yaml() {
    local yaml_file="$1"
    
    # Check if file exists and is readable
    if [[ ! -r "$yaml_file" ]]; then
        echo "❌ Cannot read YAML file: $yaml_file"
        return 1
    fi
    
    # Basic YAML syntax validation using python if available
    if command -v python3 >/dev/null 2>&1; then
        if python3 -c "import yaml; yaml.safe_load(open('$yaml_file'))" 2>/dev/null; then
            return 0
        else
            echo "❌ YAML syntax validation failed"
            return 1
        fi
    elif command -v python >/dev/null 2>&1; then
        if python -c "import yaml; yaml.safe_load(open('$yaml_file'))" 2>/dev/null; then
            return 0
        else
            echo "❌ YAML syntax validation failed"
            return 1
        fi
    else
        # Fallback: basic structure checks
        if grep -q "blocks:" "$yaml_file" && grep -q "version:" "$yaml_file"; then
            echo "⚠️  Basic structure validation passed (Python not available for full validation)"
            return 0
        else
            echo "❌ Basic YAML structure validation failed"
            return 1
        fi
    fi
}

# Show DSL statistics
function dsl_stats() {
    echo "📊 DSL Statistics"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "Blocks defined: ${#BOURGIE_DSL_BLOCKS[@]}"
    echo "Segments defined: ${#BOURGIE_DSL_SEGMENTS[@]}"
    echo "Colors in palette: ${#BOURGIE_COLORS[@]}"
    echo ""
    
    if [[ ${#BOURGIE_DSL_BLOCKS[@]} -gt 0 ]]; then
        echo "Block types:"
        for block in "${BOURGIE_DSL_BLOCKS[@]}"; do
            local block_type=$(echo "$block" | grep "type:" | head -1 | sed 's/.*type: //' | sed 's/ .*//')
            echo "  - $block_type"
        done
        echo ""
    fi
    
    if [[ ${#BOURGIE_DSL_SEGMENTS[@]} -gt 0 ]]; then
        echo "Segment types:"
        for segment in "${BOURGIE_DSL_SEGMENTS[@]}"; do
            local segment_type=$(echo "$segment" | grep "type:" | head -1 | sed 's/.*type: //' | sed 's/ .*//')
            echo "  - $segment_type"
        done
        echo ""
    fi
}

# Interactive compiler mode
function dsl_interactive() {
    echo "🎯 Bourgie DSL Interactive Compiler"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "Available commands:"
    echo "  compile <file>     - Compile DSL file to YAML"
    echo "  validate <file>    - Validate DSL file"
    echo "  example           - Generate example configuration"
    echo "  stats             - Show DSL statistics"
    echo "  help              - Show this help"
    echo "  quit              - Exit interactive mode"
    echo ""
    
    while true; do
        echo -n "dsl> "
        read -r command args
        
        case "$command" in
            "compile")
                if [[ -n "$args" ]]; then
                    dsl_compile_enhanced "$args"
                else
                    echo "Usage: compile <input-file> [output-file]"
                fi
                ;;
            "validate")
                if [[ -n "$args" ]]; then
                    dsl_compile_enhanced --validate-only "$args"
                else
                    echo "Usage: validate <input-file>"
                fi
                ;;
            "example")
                echo "Generating example configuration..."
                dsl_example
                ;;
            "stats")
                dsl_stats
                ;;
            "help")
                echo "Available commands: compile, validate, example, stats, help, quit"
                ;;
            "quit"|"exit"|"q")
                echo "Goodbye!"
                break
                ;;
            "")
                # Empty command, just show prompt again
                ;;
            *)
                echo "Unknown command: $command. Type 'help' for available commands."
                ;;
        esac
        echo ""
    done
}

# Command-line interface
function main() {
    case "$1" in
        "compile")
            shift
            dsl_compile_enhanced "$@"
            ;;
        "validate")
            shift
            dsl_compile_enhanced --validate-only "$@"
            ;;
        "example")
            echo "Generating example DSL configuration..."
            dsl_example
            ;;
        "interactive"|"i")
            dsl_interactive
            ;;
        "help"|"--help"|"-h")
            echo "Bourgie DSL Compiler"
            echo ""
            echo "Usage:"
            echo "  $0 compile <input.dsl> [output.yaml]  - Compile DSL to YAML"
            echo "  $0 validate <input.dsl>               - Validate DSL file"
            echo "  $0 example                            - Generate example configuration"
            echo "  $0 interactive                        - Start interactive mode"
            echo "  $0 help                               - Show this help"
            ;;
        "")
            # No arguments, start interactive mode
            dsl_interactive
            ;;
        *)
            echo "Unknown command: $1"
            echo "Use '$0 help' for usage information"
            exit 1
            ;;
    esac
}

# Run main if script is executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]] || [[ "${(%):-%x}" == "${0:A}" ]]; then
    main "$@"
fi