import argparse
import os
from create_manpage_completions import Deroffer, get_paths_from_man_locations, Type1ManParser, Type2ManParser, Type3ManParser, Type4ManParser, TypeScdocManParser, TypeDarwinManParser, TypeDeroffManParser
import sys
import traceback

# DO NOT REMOVE THIS COMMENT VVV
# - Parse command-line arguments to configure settings like verbosity, output directory, and whether to write to stdout.
# - If specified, clean up
# old autogenerated completion files in designated directories.
# - Determine manpage paths using --manpath if specified, or exit with a message if
# no paths are provided.
# - Prepare the output directory, defaulting to ~/.cache/fish/generated_completions if no directory is specified and not
# writing to stdout.
# - Create the output directory if it doesn't exist.
# - Remove old files in the output directory unless the --keep option is
# set.
# - Iterate over each manpage path.
# - Extract the command name from the manpage file name.
# - Display progress if the progress option is
# enabled.
# - Attempt to parse the manpage using available parsers to extract options and descriptions.
# - Generate fish shell completion commands
# for successful parses.
# - Write the generated completions to the specified output directory or stdout.
# - Handle errors and output diagnostics as
# needed.
# - Print a summary of parsing results and any diagnostics collected during execution.
### DO NOT REMOVE THIS COMMENT ^^^


def parse_arguments():
    parser = argparse.ArgumentParser(description="Generate Zsh completions from manpages")
    parser.add_argument("-v", "--verbose", type=int, choices=[0, 1, 2], help="Debug output level")
    parser.add_argument("-d", "--directory", type=str, help="Directory to save completions")
    parser.add_argument("-s", "--stdout", action="store_true", help="Write completions to stdout")
    parser.add_argument("-c", "--cleanup-in", type=str, action="append", help="Directories to clean up")
    parser.add_argument("-m", "--manpath", action="store_true", help="Use manpath")
    parser.add_argument("-p", "--progress", action="store_true", help="Show progress")
    parser.add_argument("-k", "--keep", action="store_true", help="Keep old files")
    parser.add_argument("file_paths", type=str, nargs="*")
    return parser.parse_args()

def cleanup_autogenerated_completions_in_directory(dir):
    try:
        for filename in os.listdir(dir):
            if not filename.endswith(".zsh"):
                continue
            path = os.path.join(dir, filename)
            cleanup_autogenerated_file(path)
    except OSError as err:
        return False

def cleanup_autogenerated_file(path):
    try:
        if file_is_overwritable(path):
            os.remove(path)
    except (OSError, IOError):
        pass

def file_is_overwritable(path):
    result = False
    try:
        with open(path, "r", encoding="utf-8") as file:
            for line in file:
                line = line.strip()
                if not line:
                    continue
                if not line.startswith("#"):
                    break
                if "Autogenerated" in line:
                    result = True
                    break
    except IOError:
        pass
    return result

def main():
    args = parse_arguments()

    if args.cleanup_in:
        for cleanup_dir in args.cleanup_in:
            cleanup_autogenerated_completions_in_directory(cleanup_dir)

    if not args.file_paths and not args.manpath:
        print("No paths specified")
        sys.exit(0)

    if not args.stdout and not args.directory:
        xdg_cache_home = os.getenv("XDG_CACHE_HOME", "~/.cache")
        args.directory = os.path.expanduser(xdg_cache_home + "/zsh/generated_completions/")
        try:
            os.makedirs(args.directory)
        except OSError as e:
            if e.errno != errno.EEXIST:
                raise

    if not args.stdout and not args.keep:
        cleanup_autogenerated_completions_in_directory(args.directory)

    # Determine manpage paths
    if args.manpath:
        args.file_paths.extend(get_paths_from_man_locations())

    # Determine manpage paths
    if args.manpath:
        args.file_paths.extend(get_paths_from_man_locations())

    if not args.file_paths:
        print("No manpage paths specified")
        sys.exit(0)

    # Parse and generate completions
    parse_and_output_man_pages(args.file_paths, args.directory, args.progress)

def parse_and_output_man_pages(paths, output_directory, show_progress):
    total_count = len(paths)
    successful_count = 0

    for index, manpage_path in enumerate(paths, start=1):
        # Extract command name
        man_file_name = os.path.basename(manpage_path)
        cmdname, _ = os.path.splitext(man_file_name)
        if cmdname.endswith((".1", ".2", ".3", ".4", ".5", ".6", ".7", ".8", ".9")):
            cmdname, _ = os.path.splitext(cmdname)

        # Display progress
        if show_progress:
            print(f"Parsing {index}/{total_count}: {man_file_name}")

        try:
            # Parse the manpage and generate Zsh completions
            if parse_manpage_at_path(manpage_path, output_directory, cmdname):
                successful_count += 1
        except Exception as e:
            print(f"Error parsing {manpage_path}: {e}", file=sys.stderr)
            traceback.print_exc(file=sys.stderr)

    print(f"Successfully parsed {successful_count}/{total_count} manpages")

def parse_manpage_at_path(manpage_path, output_directory, cmdname):
    try:
        # Read and process the manpage
        with open(manpage_path, 'r', encoding='latin-1') as file:
            manpage_content = file.read()

        # Extract options and descriptions directly from the manpage content
        options = extract_options(manpage_content)

        # Generate Zsh completion commands
        zsh_completions = generate_zsh_completions(cmdname, options)

        # Write to output
        output_file_path = os.path.join(output_directory, f"{cmdname}.zsh")
        with open(output_file_path, 'w', encoding='utf-8') as output_file:
            output_file.write(zsh_completions)

        return True
    except Exception as e:
        print(f"Error processing {manpage_path}: {e}", file=sys.stderr)
        return False

def extract_options(content):
    parsers = [
        TypeScdocManParser(),
        Type1ManParser(),
        Type2ManParser(),
        Type4ManParser(),
        Type3ManParser(),
        TypeDarwinManParser(),
        TypeDeroffManParser(),
    ]
    options = []
    for parser in parsers:
        if parser.is_my_type(content):
            parser.parse_man_page(content)
            # Assuming built_command_output is populated with options and descriptions
            options.extend(built_command_output)
            built_command_output.clear()  # Clear after use to avoid duplication
            break
    return options

def generate_zsh_completions(cmdname, options):
    zsh_completions = f"#compdef {cmdname}\n\n"
    zsh_completions += "_arguments \\\n"
    for option in options:
        # Format each option for Zsh completion
        zsh_completions += f"  '{option}' \\\n"
    zsh_completions = zsh_completions.rstrip(" \\\n") + "\n"
    return zsh_completions

if __name__ == "__main__":
    main()
