#!/usr/bin/env zsh

# Generated by Bourgie DSL Compiler
# This file contains custom prompt functions defined in the DSL
# Compatible with oh-my-posh's posh_setcontext mechanism

# Custom function: _bourgie_custom_fn_path_left_0
# Source path: blocks[0].segments[0]
# Template variable: {{ .Env._BOURGIE_CUSTOM_FN_PATH_LEFT_0_OUTPUT }}
function _bourgie_custom_fn_path_left_0() {
    local icon="📁" [[ "$PWD" == "$HOME" ]] && icon="🏠" [[ "$PWD" == *".config"* ]] && icon="⚙️" [[ "$PWD" == *"dev"* || "$PWD" == *"code"* ]] && icon="💻" echo "${icon} ${PWD} "
}

# Custom function: _bourgie_custom_fn_git_left_1
# Source path: blocks[0].segments[1]
# Template variable: {{ .Env._BOURGIE_CUSTOM_FN_GIT_LEFT_1_OUTPUT }}
function _bourgie_custom_fn_git_left_1() {
    [[ -z "$POSH_GIT_STATUS" ]] && return
    local status="🌿 $POSH_GIT_HEAD"
    if [[ "$POSH_GIT_WORKING_CHANGED" == "true" || "$POSH_GIT_STAGING_CHANGED" == "true" ]]; then [[ "$POSH_GIT_WORKING_CHANGED" == "true" ]] && status+=" 📝" [[ "$POSH_GIT_STAGING_CHANGED" == "true" ]] && status+=" 📦" else status+=" ✨" fi
    [[ "$POSH_GIT_STASH_COUNT" -gt 0 ]] && status+=" 📚$POSH_GIT_STASH_COUNT"
    echo "${status} "
}

# Custom function: _bourgie_custom_fn_text_left_2
# Source path: blocks[0].segments[2]
# Template variable: {{ .Env._BOURGIE_CUSTOM_FN_TEXT_LEFT_2_OUTPUT }}
function _bourgie_custom_fn_text_left_2() {
    local indicators=() [[ "$ENABLE_DOCKER_PROMPT" == "true" ]] && indicators+=("🐳") [[ "$ENABLE_NODE_PROMPT" == "true" ]] && indicators+=("⬢") [[ -n "$VIRTUAL_ENV" ]] && indicators+=("🐍") [[ -n "$SSH_CLIENT" ]] && indicators+=("🔗")
    [[ ${#indicators[@]} -eq 0 ]] && return
    local IFS=" " echo "[${indicators[*]}] "
}

# Custom function: _bourgie_custom_fn_text_left_3
# Source path: blocks[0].segments[3]
# Template variable: {{ .Env._BOURGIE_CUSTOM_FN_TEXT_LEFT_3_OUTPUT }}
function _bourgie_custom_fn_text_left_3() {
    local char="❯" local color="#00CED1"
    if git rev-parse --git-dir >/dev/null 2>&1; then char="🚀" color="#90EE90" fi
    if [[ -n "$SSH_CLIENT" ]]; then char="🌐" color="#FFB6C1" fi
    if [[ "$EUID" -eq 0 ]]; then char="👑" color="#FF6347" fi
    echo "${char} "
}

# Main context setting function - executes all custom functions
# This function is called by oh-my-posh before each prompt render
function set_poshcontext() {
    # Execute _bourgie_custom_fn_path_left_0 and export result
    export _BOURGIE_CUSTOM_FN_PATH_LEFT_0_OUTPUT="$(_bourgie_custom_fn_path_left_0)"
    # Execute _bourgie_custom_fn_git_left_1 and export result
    export _BOURGIE_CUSTOM_FN_GIT_LEFT_1_OUTPUT="$(_bourgie_custom_fn_git_left_1)"
    # Execute _bourgie_custom_fn_text_left_2 and export result
    export _BOURGIE_CUSTOM_FN_TEXT_LEFT_2_OUTPUT="$(_bourgie_custom_fn_text_left_2)"
    # Execute _bourgie_custom_fn_text_left_3 and export result
    export _BOURGIE_CUSTOM_FN_TEXT_LEFT_3_OUTPUT="$(_bourgie_custom_fn_text_left_3)"
}

# Auto-execute set_poshcontext if not disabled
if [[ "$BOURGIE_DSL_NO_AUTO_CONTEXT" != "true" ]]; then
    set_poshcontext
fi
